version: '3.9'

services:

  postgres:
    image: postgres:${PG_VERSION}
    container_name: ${PROJECT_NAME}_postgres
    restart: always
    env_file:
      - .env
    environment:
      # env vars specific to postgres image used on first boot
      - POSTGRES_USER=${PG_SUPERUSER}
      - POSTGRES_PASSWORD=${PG_SUPERUSER_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
      - PGPORT=${PG_PORT}
      - PGTZ=${PG_TZ}
      - TZ=${PG_TZ}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./volumes/postgres/tmp:/tmp

  web:
    build: .
    restart: on-failure
    depends_on:
     - postgres
    env_file:
      - .env
    environment:
      - TZ="Europe/Moscow"
    ports:
      - "8000:8000"

